<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Karthick" name="test12" tests="8" failures="1" timestamp="29 Aug 2020 05:52:39 GMT" time="9.088" errors="0">
  <testcase name="b_m1" time="3.454" classname="com.testng.basics.AnnotatinSample">
    <failure type="java.lang.AssertionError" message="expected [Category name is already exist. please entesdsdr new category name] but found [Category name is already exist. please enter new category name]">
      <![CDATA[java.lang.AssertionError: expected [Category name is already exist. please entesdsdr new category name] but found [Category name is already exist. please enter new category name]
	at com.testng.basics.AnnotatinSample.b_m1(AnnotatinSample.java:83)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- b_m1 -->
  <testcase name="c_m3" time="0.0" classname="com.testng.basics.AnnotatinSample"/>
  <testcase name="c_m1" time="0.0" classname="com.testng.basics.AnnotatinSample2"/>
  <testcase name="c_m3" time="0.0" classname="com.testng.basics.AnnotatinSample2"/>
  <testcase name="m4" time="0.0" classname="com.testng.basics.AnnotatinSample"/>
  <testcase name="m2" time="0.0" classname="com.testng.basics.AnnotatinSample2"/>
  <testcase name="m4" time="0.001" classname="com.testng.basics.AnnotatinSample2"/>
  <testcase name="a_m2" time="0.416" classname="com.testng.basics.AnnotatinSample"/>
</testsuite> <!-- test12 -->
